---
- name: Set up sonar-secret.txt for SonarQube
  hosts: localhost
  connection: local
  tasks:
    - name: Make directory /home/sonarqube/.sonar
      community.docker.docker_container_exec:
        container: sonarqube-sonarqube-1
        command: /bin/bash -c "mkdir -p /home/sonarqube/.sonar && chown -R sonarqube /home/sonarqube"
        user: root
    - name: Copy secretKey
      community.docker.docker_container_copy_into:
        container: sonarqube-sonarqube-1
        content: '{{ lookup("file", "files/sonar-secret.txt") }}'
        container_path: /home/sonarqube/.sonar/sonar-secret.txt
        mode: 0640
